services:
  ldio:
    image: ldes/ldi-orchestrator:2.14.0
    ports:
      - 8081:8080
    volumes:
      - ./application.yml:/ldio/application.yml:ro
      - ./startup.sh:/mnt/data/startup.sh:ro
    command: /bin/sh /mnt/data/startup.sh
    networks:
      - ldes
    depends_on:
      database:
        condition: "service_healthy"
  database:
    image: redpencil/virtuoso:1.4.0-rc.1
    ports:
      - 8890:8890
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
      DBA_PASSWORD: mypassword
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    healthcheck:
      test: ["CMD", "isql-v", "1111", "dba", "mypassword", "EXEC=SELECT 1;"]
      interval: 10s
      timeout: 2s
      retries: 20
    restart: always
    networks:
      - ldes
networks:
  ldes:
    driver: bridge